language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-25

    - extra-google-m2repository
    - extra-android-m2repository

env:
  global:
    - GRADLE_OPTS="-Xms128m -Xmx512m -XX:MaxPermSize=512m"

script: ./gradlew build